export type VehicleInput = {
  vehicle_type?: string;
  brand: string;
  model: string;
  version: string;
  year: number;
  km: number;
  transmission: string;
  fuel: string;
  color: string;
  options: string;
  condition: string;
  city: string;
  state: string;
  history: string;
  revisions: string;
  notes: string;
  photos: string[];
  query?: string;
  fipe_code?: string;
};

export type ValuationResult = {
  vehicle: VehicleInput;
  valuation: {
    fipe_simulated: number;
    fipe_real?: number | null;
    mode?: "DEMO" | "REAL";
    data_badge?: string;
    confidence_score?: number;
    confidence_label?: string;
    comparable_count?: number;
    comparables?: { title: string; price: number; year: number; mileage: number; city: string; state: string; source: string; similarity_score: number; url?: string; collected_at?: string }[];
    sources?: string[];
    fipe_source?: string;
    fipe_reference_month?: string | null;
    methodology_note?: string;
    valuation_explanation_text?: string;
    executive_market_insight?: string;
    market_temperature_detail?: string;
    regional_explanation?: string;
    positive_impact_total?: number;
    negative_impact_total?: number;
    valuation_explanation?: { factor: string; impact_value: number; impact_direction: string; weight: number; reason: string }[] | string;
    comparable_analysis?: { title?: string; source?: string; price: number; similarity_score: number; km_difference: number; regional_similarity: number; market_distance: number; valuation_impact: number; reading: string }[];
    negotiation_intelligence?: { quick_sale_price?: number; ideal_listing_range?: number[]; negotiation_floor?: number; negotiation_ceiling?: number; estimated_negotiation_margin?: number; estimated_sale_time?: string };
    low_confidence_message?: string;
    analysis_date?: string;
    comparables_used?: number;
    comparables_count?: number;
    regional_scope?: string;
    year_range?: number[];
    mileage_range?: { min: number; max: number };
    average_similarity_score?: number;
    outliers_removed?: number;
    fipe_weight?: number;
    real_market_weight?: number;
    weighted_median_price?: number;
    confidence_explanation?: string;
    liquidity_explanation?: string;
    methodology_summary?: string;
    market_snapshot?: { status: string; summary: string; demand: string; supply: string; trend: string };
    price_dispersion?: { min: number; p25: number; p50: number; median: number; p75: number; max: number; dispersion_ratio: number; dispersion_label: string };
    market_reference: number;
    quick_sale_price: number;
    ideal_price: number;
    recommended_top_price?: number;


    selling_strategy?: { recommended_listing_price?: number; safe_price_range?: number[]; quick_sale_price?: number; probable_ceiling?: number; overvaluation_risk?: number; recommended_adjustment?: string; resistance_price?: number; strategy_label?: string; strategy_reason?: string };
    price_positioning?: { market_position_percentile?: number; competitiveness_level?: string; pricing_pressure?: string; market_resistance?: string; positioning_score?: number; positioning_summary?: string; dispersion_used?: number };
    buyer_behavior?: { buyer_price_sensitivity?: string; km_sensitivity?: string; regional_buyer_profile?: string; buyer_behavior_insights?: string[]; primary_buyer_argument?: string };
    market_insights?: { market_temperature_label?: string; market_temperature_score?: number; market_thesis?: string; executive_market_insight_v2?: string; market_insight_bullets?: string[] };
    liquidity_pressure?: { pressure_score?: number; sale_probability?: number; estimated_market_resistance?: string; resistance_price?: number; liquidity_pressure_summary?: string };
    selling_decision?: { listing_price?: number; ideal_close_range_min?: number; ideal_close_range_max?: number; minimum_recommended_price?: number; resistance_price?: number; stuck_risk_level?: string; stuck_risk_reason?: string; review_price_after_days?: number; suggested_price_cut_percent?: number; negotiation_signal?: string; negotiation_message?: string; price_defense_arguments?: string[]; seller_summary?: string; psychological_price_note?: string; proposal_reference?: { green_from?: number; yellow_from?: number; red_below?: number } };
    market_position_percentile?: number;
    competitiveness_level?: string;
    pricing_pressure?: string;
    market_resistance?: string;
    pressure_score?: number;
    sale_probability?: number;
    estimated_market_resistance?: string;
    market_temperature_label?: string;
    market_temperature_score?: number;
    executive_market_insight_v2?: string;
    market_insight_bullets?: string[];
    buyer_behavior_insights?: string[];
    buyer_price_sensitivity?: string;
    recommended_listing_price?: number;
    safe_price_range?: number[];
    probable_ceiling?: number;
    overvaluation_risk?: number;
    recommended_adjustment?: string;
    listing_price?: number;
    ideal_close_range_min?: number;
    ideal_close_range_max?: number;
    minimum_recommended_price?: number;
    resistance_price?: number;
    stuck_risk_level?: string;
    stuck_risk_reason?: string;
    review_price_after_days?: number;
    suggested_price_cut_percent?: number;
    negotiation_signal?: string;
    negotiation_message?: string;
    price_defense_arguments?: string[];
    seller_summary?: string;
    psychological_price_note?: string;
    mcv_intelligence_version?: string;
    mcv_intelligence?: {
      comparables?: Record<string, unknown>;
      liquidity?: Record<string, unknown>;
      negotiation?: Record<string, unknown>;
      confidence?: Record<string, unknown>;
      regional?: Record<string, unknown>;
      trends?: Record<string, unknown>;
      selling_strategy?: Record<string, unknown>;
      price_positioning?: Record<string, unknown>;
      buyer_behavior?: Record<string, unknown>;
      market_insights?: Record<string, unknown>;
      liquidity_pressure?: Record<string, unknown>;
      selling_decision?: Record<string, unknown>;
      methodology?: string[];
    };
    similarity_score?: number;
    regional_similarity?: number;
    km_similarity?: number;
    market_distance?: number;
    liquidity_level?: string;
    market_temperature?: string;
    sale_velocity?: string;
    demand_index?: number;
    recommended_price?: number;
    negotiation_ceiling?: number;
    negotiation_floor?: number;
    estimated_negotiation_margin?: number;
    confidence_level?: string;
    confidence_reason?: string;
    analysis_quality?: string;
    regional_multiplier?: number;
    regional_market_temperature?: string;
    regional_price_delta?: number;
    trend_direction?: string;
    weekly_trend?: string;
    monthly_trend?: string;
    [key: string]: unknown;
    negotiation_range: number[];
    vehicle_score: number;
    liquidity_score: number;
    liquidity_label?: string;
    regional_comparable_count?: number;
    region_used?: string;
    attractiveness_score: number;
    market_delta_vs_fipe_pct: number;
    chart: { label: string; value: number }[];
    liquidity_curve: { month: string; score: number }[];
  };
  insights: {
    summary: string;
    analysis: string;
    strengths: string[];
    attention_points: string[];
    pricing_recommendation: string;
    negotiation_recommendation: string;
    market_perception: string;
  };
  ads: Record<string, string>;
  image_quality: { name: string; quality_score: number; suggestion: string }[];
};
